# Generated by Django 4.2.4 on 2023-08-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='payments', to='lessons.lesson'),
        ),
    ]
